export const componentsList = [
  {
    title: "ActionSheet",
    link: "/elements/actionsheet",
    url: "https://i.imgur.com/WOc44VL.png",
    darkUrl: "https://i.imgur.com/lXBHovv.png",
  },
  {
    title: "AlertDialog",
    link: "/elements/alert-dialog",
    url: "https://i.imgur.com/8wbsESv.png",
    darkUrl: "https://i.imgur.com/LRCCXxT.png",
  },
  {
    title: "Alert",
    link: "/elements/alert",
    url: "https://i.imgur.com/xfmvFSy.png",
    darkUrl: "https://i.imgur.com/C8yWYco.png",
  },
  {
    title: "Avatar",
    link: "/elements/avatar",
    url: "https://i.imgur.com/EqA9Hk0.png",
    darkUrl: "https://i.imgur.com/JXre3tG.png",
  },
  {
    title: "Accordion",
    link: "/elements/accordion",
    url: "https://i.imgur.com/kFWvTEZ.png",
    darkUrl: "https://i.imgur.com/Q2dhSXA.png",
  },
  {
    title: "Animation",
    link: "/elements/animation",
    url: "https://i.imgur.com/kFWvTEZ.png",
    darkUrl: "https://i.imgur.com/Q2dhSXA.png",
  },
  {
    title: "Badge",
    link: "/elements/badge",
    url: "https://i.imgur.com/eguhrI7.png",
    darkUrl: "https://i.imgur.com/a3Sx1JL.png",
  },
  {
    title: "Box",
    link: "/elements/box",
    url: "https://i.imgur.com/3rXWRNQ.png",
    darkUrl: "https://i.imgur.com/nA1FGmN.png",
  },
  {
    title: "Button",
    link: "/elements/button",
    url: "https://i.imgur.com/Hkurc7l.png",
    darkUrl: "https://i.imgur.com/hS1TqJ7.png",
  },
  {
    title: "Card",
    link: "/elements/card",
    url: "https://i.imgur.com/At8sHdO.png",
    darkUrl: "https://i.imgur.com/g37yBPg.png",
  },
  {
    title: "Center",
    link: "/elements/center",
    url: "https://i.imgur.com/fN5RCAV.png",
    darkUrl: "https://i.imgur.com/gmV2Fil.png",
  },
  {
    title: "Checkbox",
    link: "/elements/checkbox",
    url: "https://i.imgur.com/fZPMCl3.png",
    darkUrl: "https://i.imgur.com/1c2clr3.png",
  },
  {
    title: "Divider",
    link: "/elements/divider",
    url: "https://i.imgur.com/jqlr7CA.png",
    darkUrl: "https://i.imgur.com/2KXPQRB.png",
  },
  {
    title: "Drawer",
    link: "/elements/drawer",
    url: "https://i.imgur.com/LlB5AI5.png",
    darkUrl: "https://i.imgur.com/0pVIYjO.png",
  },
  {
    title: "Fab",
    link: "/elements/fab",
    url: "https://i.imgur.com/6lkv7mK.png",
    darkUrl: "https://i.imgur.com/sa0hOQc.png",
  },
  {
    title: "FormControl",
    link: "/elements/form-control",
    url: "https://i.imgur.com/8QpwG4G.png",
    darkUrl: "https://i.imgur.com/zf6CD5X.png",
  },
  {
    title: "Grid",
    link: "/elements/grid",
    url: "https://i.imgur.com/xS7rIHh.png",
    darkUrl: "https://i.imgur.com/r6HtWus.png",
  },
  {
    title: "Heading",
    link: "/elements/heading",
    url: "https://i.imgur.com/iLgtAcF.png",
    darkUrl: "https://i.imgur.com/or5K0UG.png",
  },
  {
    title: "HStack",
    link: "/elements/hstack",
    url: "https://i.imgur.com/zMeYQ2r.png",
    darkUrl: "https://i.imgur.com/sxWxT2s.png",
  },
  {
    title: "Icon",
    link: "/elements/icon",
    url: "https://i.imgur.com/wrq05q6.png",
    darkUrl: "https://i.imgur.com/sCURs3s.png",
  },
  {
    title: "Image",
    link: "/elements/image",
    url: "https://i.imgur.com/7YMLZNW.png",
    darkUrl: "https://i.imgur.com/Znp5FNr.png",
  },
  {
    title: "Input",
    link: "/elements/input",
    url: "https://i.imgur.com/I9xTmZ4.png",
    darkUrl: "https://i.imgur.com/I2zxm8c.png",
  },
  {
    title: "Link",
    link: "/elements/link",
    url: "https://i.imgur.com/4wQcdzK.png",
    darkUrl: "https://i.imgur.com/7faES6e.png",
  },
  {
    title: "Menu",
    link: "/elements/menu",
    url: "https://i.imgur.com/yfTtp1X.png",
    darkUrl: "https://i.imgur.com/8jIXxUv.png",
  },
  {
    title: "Modal",
    link: "/elements/modal",
    url: "https://i.imgur.com/JN17X3h.png",
    darkUrl: "https://i.imgur.com/ik0l5yw.png",
  },
  {
    title: "Popover",
    link: "/elements/popover",
    url: "https://i.imgur.com/ucORZwJ.png",
    darkUrl: "https://i.imgur.com/mbGFXOv.png",
  },
  {
    title: "Portal",
    link: "/elements/portal",
    url: "https://i.imgur.com/jY7HA3A.png",
    darkUrl: "https://i.imgur.com/9wxdk9Z.png",
  },
  {
    title: "Pressable",
    link: "/elements/pressable",
    url: "https://i.imgur.com/OeevpAV.png",
    darkUrl: "https://i.imgur.com/6IFqABT.png",
  },
  {
    title: "Progress",
    link: "/elements/progress",
    url: "https://i.imgur.com/Z3uiwmT.png",
    darkUrl: "https://i.imgur.com/1l5mrcN.png",
  },
  {
    title: "Radio",
    link: "/elements/radio",
    url: "https://i.imgur.com/QXCVfb5.png",
    darkUrl: "https://i.imgur.com/Oh87yLk.png",
  },
  {
    title: "Select",
    link: "/elements/select",
    url: "https://i.imgur.com/E1M54Np.png",
    darkUrl: "https://i.imgur.com/jyB3256.png",
  },
  {
    title: "Skeleton",
    link: "/elements/skeleton",
    url: "https://i.imgur.com/c65rk9I.png",
    darkUrl: "https://i.imgur.com/AGl2kYx.png",
  },
  {
    title: "Slider",
    link: "/elements/slider",
    url: "https://i.imgur.com/DRS1gIZ.png",
    darkUrl: "https://i.imgur.com/UxqfgHH.png",
  },
  {
    title: "Spinner",
    link: "/elements/spinner",
    url: "https://i.imgur.com/mxiaDbN.png",
    darkUrl: "https://i.imgur.com/4sPAI8m.png",
  },
  {
    title: "Switch",
    link: "/elements/switch",
    url: "https://i.imgur.com/SVcRBpp.png",
    darkUrl: "https://i.imgur.com/eEmyfhZ.png",
  },
  // {
  //   title: "Table",
  //   link: "/elements/table",
  //   url: "https://i.imgur.com/qQ3oUUq.png",
  //   darkUrl: "https://i.imgur.com/bGh3iWR.png",
  // },
  {
    title: "Text",
    link: "/elements/text",
    url: "https://i.imgur.com/vp6ui7d.png",
    darkUrl: "https://i.imgur.com/XMZvanC.png",
  },
  {
    title: "TextArea",
    link: "/elements/textarea",
    url: "https://i.imgur.com/DEhCtqY.png",
    darkUrl: "https://i.imgur.com/rHu35J0.png",
  },
  {
    title: "Toast",
    link: "/elements/toast",
    url: "https://i.imgur.com/2NZj9gR.png",
    darkUrl: "https://i.imgur.com/7UQomgU.png",
  },
  {
    title: "Tooltip",
    link: "/elements/tooltip",
    url: "https://i.imgur.com/OyRsX4f.png",
    darkUrl: "https://i.imgur.com/VzxzCVU.png",
  },
  {
    title: "VStack",
    link: "/elements/vstack",
    url: "https://i.imgur.com/d7QcAkw.png",
    darkUrl: "https://i.imgur.com/2ivkRp7.png",
  },
];
